### ISSUE TITLE
Get BitCoin Price data

### ISSUE THREAD

**Issue by t-d-o-g** [t-d-o-g/bitcoin-oracle#9]

**Comment by t-d-o-g** [comment]
CoinMarketCap API recommended to me by coworker who has used it in project before.
https://coinmarketcap.com/api/

**Comment by t-d-o-g** [comment]
@palshah28 
found this API for real time price of bitcoin
found this one for historical data price --
https://api.coindesk.com/v1/bpi/currentprice.json
https://api.coindesk.com/v1/bpi/historical/close.json?start=2014-07-01&end=2018-07-01

**Comment by t-d-o-g** [comment]
CoinDesk looks good

**Comment by t-d-o-g** [comment]
Would like to get price data hourly, but seems that it is only available daily from CoinDesk

**Comment by palshah28** [comment]
price data (current) done from coindesk.. code pushed
